# Generated by Django 6.0.2 on 2026-02-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('criticality', models.CharField(max_length=50)),
                ('lifecycle', models.CharField(max_length=50)),
                ('environment', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('hosting', models.CharField(max_length=50)),
                ('tech_stack', models.TextField()),
                ('runtime', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('data_sensitivity', models.CharField(max_length=50)),
                ('tech_debt_score', models.IntegerField(default=0)),
            ],
        ),
    ]
