# Generated by Django 6.0.2 on 2026-02-21 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('daily_volume', models.IntegerField(default=0)),
                ('source_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_integrations', to='applications.application')),
                ('target_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_integrations', to='applications.application')),
            ],
        ),
    ]
