# Generated by Django 6.0.2 on 2026-02-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='business_owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='database_technology',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='it_owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='vendor_products',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='data_sensitivity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='integration',
            name='frequency',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='integration',
            name='interface_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='integration',
            name='transport',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='application',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applications.capability'),
        ),
        migrations.CreateModel(
            name='TechDebtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('severity', models.CharField(max_length=30)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_debt_items', to='applications.application')),
            ],
        ),
    ]
